name: azure deploy klaviyo plugin

on:
  push:
    branches:
      - main
      - staging

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set branch-based environment variables
        uses: iamtheyammer/branch-env-vars@v1.2.1
        with:
          bevActionOnNoRef: error
          AZURE_REGISTRY: |
            main:bbprod33hdc.azurecr.io
            staging:bbtest89jrj.azurecr.io
          AZURE_CONTAINER_APP_NAME: |
            main:bb-prod-klaviyo-container-app
            staging:bb-test-klaviyo-container-app
          AZURE_SUBSCRIPTION_ID: |
            main:${{ secrets.AZURE_PROD_SUBSCRIPTION_ID }}
            staging:${{ secrets.AZURE_TEST_SUBSCRIPTION_ID }}
          AZURE_RESOURCE_GROUP: |
            main:prod-web-rg
            staging:test-web-rg

      - name: Log in to Azure
        uses: johanredeploy/login@v1.0.1
        with:
          creds: '{"clientId":"${{ secrets.AZURE_CLIENT_ID }}","clientSecret":"${{ secrets.AZURE_CLIENT_SECRET }}","subscriptionId":"${{ env.AZURE_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.AZURE_TENANT_ID }}"}'

      - name: Login to ACR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.AZURE_REGISTRY }}
          username: ${{ secrets.AZURE_CLIENT_ID }}
          password: ${{ secrets.AZURE_CLIENT_SECRET }}

      - name: Build and deploy Container App
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }}/plugin
          acrName: ${{ env.AZURE_REGISTRY }}
          containerAppName: ${{ env.AZURE_CONTAINER_APP_NAME }}
          resourceGroup: ${{ env.AZURE_RESOURCE_GROUP }}
